export default [
    { word: "carro", tip:"Meio de Transporte" },
    { word: "banana", tip:"Fruta" },
    { word: "abacate", tip: "Fruta" },
    { word: "amarelo", tip: "Cor" },
    { word: "girafa", tip: "Animal" },
    { word: "parque", tip: "Lugar"},
    { word: "elefante", tip: "Animal"},
    { word: "celular", tip: "Dispositivo"},
    { word: "limonada", tip: "Bebida"},
    { word: "branco", tip: "Cor"},
    { word: "bolo", tip: "Doce"},
    { word: "copo", tip: "Recipiente"},
    { word: "chuveiro", tip: "Água"},
    { word: "coelho", tip: "Animal"},
    { word: "esfirra", tip: "Salgado"},
    { word: "cachorro", tip: "Animal"},
    { word: "amendoim", tip: "Cereal"},
    { word: "pneumonia", tip: "Doença"},
    { word: "magenta", tip: "Cor"},
    { word: "faca", tip: "Cozinha"},
    { word: "geladeira", tip: "Cozinha"},
    { word: "setembro", tip: "Mês"},
    { word: "picanha", tip: "Churrasco"},
    { word: "espetinho", tip: "Churrasco"},
    { word: "cerveja", tip: "Bebida"},
    { word: "suco", tip: "Bebida"},
    { word: "espelho", tip: "Banheiro"},
    { word: "embarque", tip: "Aeroporto"},
    { word: "Pedreiro", tip: "Profissão"},
    { word: "javascript", tip: "Linguagem"},
    { word: "camista", tip: "Roupa"},
    { word: "monitor", tip: "Tela"},
    { word: "banco", tip: "Dinheiro"},
    { word: "marte", tip: "Planeta"},
    { word: "ford", tip: "Marca"},
    { word: "futebol", tip: "Jogo"},
    { word: "truco", tip: "Jogo"},
    { word: "salvador", tip: "Cidade"},
    { word: "sorocaba", tip: "Cidade"},
    { word: "inverno", tip: "Estação"},
    { word: "novela", tip: "Ator"},
]
